name = "autodiscover-email-settings"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
COMPANY_NAME = "Company"
SUPPORT_URL = "https://autodiscover.example.com"
DOMAIN = "example.com"

IMAP_HOST = "imap.example.com"
IMAP_PORT = "993"
IMAP_SOCKET = "SSL"

POP_HOST = ""
POP_PORT = ""
POP_SOCKET = ""

SMTP_HOST = "smtp.example.com"
SMTP_PORT = "587"
SMTP_SOCKET = "STARTTLS"

MOBILESYNC_URL = ""
MOBILESYNC_NAME = ""

LDAP_HOST = ""
LDAP_PORT = ""
LDAP_SOCKET = ""
LDAP_BASE = ""
LDAP_USER_FIELD = ""
LDAP_USER_BASE = ""
LDAP_SEARCH = ""

PROFILE_IDENTIFIER = ""
PROFILE_UUID = ""
MAIL_UUID = ""
LDAP_UUID = ""
